// Every Cloudinary capability Pravaha uses, where a visitor can see it working, and where it lives in the code.
// The /judges page renders this list, so it must stay true: tests/unit/capabilities.test.ts checks every
// `code` path exists in the repository.

export type Capability = { name: string; does: string; see: string; code: string };

export const CAPABILITIES: Capability[] = [
  { name: "Signed upload preset + Upload Widget", does: "Browser-to-Cloudinary video upload with real progress; the server only signs.", see: "Studio, /try", code: "src/app/api/upload-signature/route.ts" },
  { name: "auto_transcription", does: "Word-timed transcript at upload: the corpus for Find, Ask and subtitles.", see: "Watch → Transcript", code: "src/lib/ingest.ts" },
  { name: "auto_chaptering", does: "AI chapters on the seek bar and as search context.", see: "Watch → Chapters", code: "src/lib/chapters.ts" },
  { name: "Translated transcripts (hi-IN)", does: "Hindi subtitles generated by Cloudinary, plus asking in Hindi.", see: "Watch → subtitles menu", code: "src/lib/subtitles.ts" },
  { name: "Video Player + HLS streaming profile", does: "Adaptive 720p/360p/180p ladder that survives slow mobile data.", see: "Any session", code: "src/components/Player.tsx" },
  { name: "e_preview + fl_getinfo + fl_sprite", does: "AI highlights graph, seek-bar thumbnails and 6-second hover previews.", see: "Library cards, Watch", code: "src/lib/media.ts" },
  { name: "so_/eo_ trims + c_fill,ar_9:16,g_auto", does: "Moments: any sentence becomes a vertical clip that tracks the speaker.", see: "Share as Moment", code: "src/lib/media.ts" },
  { name: "Timed l_text layers", does: "Word-accurate burned-in captions and speaker labels, exact on trimmed clips.", see: "Moments, reels", code: "src/lib/media.ts" },
  { name: "l_video + fl_splice", does: "Answer Reels, Study Pack reels, Learning Paths and Compare Reels: moments from many sessions as one video.", see: "Ask, /learn, /concepts", code: "src/lib/media.ts" },
  { name: "g_auto thumbnails + gradient/text share cards", does: "Open Graph images for every moment, answer, course and concept: one URL, no image service.", see: "/m, /a, /p, /concepts", code: "src/lib/media.ts" },
  { name: "f_auto, q_auto", does: "Best format and quality for each device on every derived asset.", see: "Everywhere", code: "src/lib/media.ts" },
  { name: "Notification webhooks (signed)", does: "Upload to ready with no polling; signature and replay window verified.", see: "Studio status", code: "src/lib/webhook-signature.ts" },
  { name: "Incoming transformation eo_60", does: "Public trial uploads keep only 60 seconds, so abuse cannot cost more.", see: "/try", code: "src/lib/trial-policy.ts" },
  { name: "Tags + contextual metadata", does: "Each asset carries its concepts, speaker and language inside Cloudinary.", see: "Studio → Cloudinary asset index", code: "src/lib/cloudinary-index.ts" },
  { name: "Search API", does: "Reads the tagged assets back from Cloudinary itself.", see: "Studio → Cloudinary asset index", code: "src/lib/cloudinary-index.ts" },
];
